### PR TITLE
Bytesize

### LINKED ISSUE #135: Plugin parameter validation fails when using scientific notation
Large numbers are marshalled in scientific notation (e.g. `1e9`), which when unmarshalled with the `yaml` package to an `interface{}`, yields a `float64`. This is problematic with our parameter validation code because it errors when `1e9` is specified as the value of a parameter with the `int` type. 

A small, reproducing example: 
```yaml
# config.yaml
pipeline:
  - type: my_plugin
    test_int: 1e9

  - type: stdout
```
```yaml
# plugins/my_plugin.yaml
parameters:
  test_int:
    required: true
    type: int

pipeline:
  - type: generate_input
    count: {{ .test_int }}
```
```
❯ stanza -c ./config.yaml --plugin_dir ./plugins 2>&1  | jq
{
  "level": "error",
  "timestamp": "2020-10-02T10:50:21.594-0400",
  "message": "Failed to build agent",
  "error": "build operator configs: failed to render plugin config: plugin parameter failed validation: {\"error_message\":\"parameter must be an integer\",\"plugin_parameter\":\"test_int\",\"plugin_type\":\"my_plugin\"}"
}
```

### LINKED ISSUE #153: Add a config type for human-readable byte sizes (e.g. `3MB`)
Currently, we have a few places in our codebase that take a number of bytes as an argument. In some of these cases (e.g. disk buffer), these can get unreadably large. For example, 1GiB is 1073741824 bytes. We should consider adding a type (like `helper.Duration`) that provides custom unmarshalling of byte-like values into an integer. 

[`go-humanize`](https://godoc.org/github.com/dustin/go-humanize#ParseBytes) may be useful here, but this seems like a simple enough pattern that we should consider avoiding the extra dependency.

### PR DESCRIPTION
**Pull request by camdencheek**
## Description of Changes

Adds type `helper.ByteSize` that allows users to configure byte values in a more human-readable format. For example, the file input `max_log_size` can now be configured as `5000`, `5kb`, `4.88KiB`, or `5e3`. Fixes #135. Closes #153.

## **Please check that the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Add a changelog entry (for non-trivial bug fixes / features)
- [x] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.7069266|+0.06896198|127.53677|+5.4418106|
|1|5000|6.1035614|-0.2068963|131.43036|-5.7834015|
|1|10000|11.689835|-0.29320717|140.1444|+2.9637604|
|1|50000|61.389187|+0.50632095|182.91797|+6.6404877|
|1|100000|115.65875|-0.7556839|230.99232|+4.305771|
|10|100|2.1725676|-0.31029534|128.5058|-0.22103882|
|10|500|6.68982|-0.39653492|132.82718|+0.97117615|
|10|1000|13.103878|-1.0001106|141.7853|-1.8127594|
|10|5000|62.43427|-3.0126457|181.76602|-1.5596771|
|10|10000|125.85234|-1.4095917|232.84941|+7.7113495|

File: operator/helper/bytesize_test.go [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+		{`1kib`, 1024, false},
+		{`1KiB`, 1024, false},
+		{`1mb`, 1000 * 1000, false},
+		{`1mib`, 1024 * 1024, false},
+		{`1gb`, 1000 * 1000 * 1000, false},
+		{`1gib`, 1024 * 1024 * 1024, false},
+		{`1tb`, 1000 * 1000 * 1000 * 1000, false},
+		{`1tib`, 1024 * 1024 * 1024 * 1024, false},
+		{`1pB`, 1000 * 1000 * 1000 * 1000 * 1000, false},
+		{`1pib`, 1024 * 1024 * 1024 * 1024 * 1024, false},
```
Comment (djaglowski) [inline operator/helper/bytesize_test.go:97]: These cases appear to be duplicates.

At a higher level though, should we be able unmarshal the same values with either json or yaml? If so, it would probably make sense to share a single set of test inputs.

**Review by djaglowski — APPROVED** [review]
Looks great.

File: operator/helper/bytesize_test.go (hunk 1 above)
Comment (camdencheek) [reply operator/helper/bytesize_test.go:97]: They're not quite duplicates, they're just without quotes `""`. However, since YAML is a superset of JSON, all the JSON tests should work with YAML, so we can definitely reduce some duplication

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.7414112|+0.05167973|123.26549|-0.12661743|
|1|5000|5.8794527|-0.5517664|130.87096|-6.2828674|
|1|10000|11.603688|-0.18964481|139.57623|-1.0744934|
|1|50000|60.035934|+0.30843735|181.43306|+7.2832794|
|1|100000|116.59377|+0.587677|586.5663|+254.0058|
|10|100|2.2587156|-0.068936825|126.91137|+0.6569214|
|10|500|6.689919|-0.15509129|136.07152|+5.5567017|
|10|1000|13.138194|-0.0689764|141.86234|-3.2435303|
|10|5000|66.7957|+3.1555786|206.87285|+23.123795|
|10|10000|125.47631|+1.625885|554.42944|+294.2969|
